"""
ai_analyzer.py — AI-Assisted Analysis using the Anthropic Claude API
=====================================================================
Week 4 - Cybersecurity Portfolio | Author: Haseeb | IMSciences, Peshawar

This module sends vulnerability findings to Claude and receives:
  - Plain-English explanation of the finding
  - Severity assessment with reasoning
  - Concrete remediation steps for developers
  - Real-world attack scenario description

IMPORTANT DISCLAIMER:
  All output from this module is AI-assisted interpretation.
  It supplements — and does not replace — manual analysis.
  Every finding is clearly labelled as AI-generated.

Prerequisite:
  Set the ANTHROPIC_API_KEY environment variable before running.
  export ANTHROPIC_API_KEY="sk-ant-..."
"""

import os
import json
import re
import anthropic


# ─────────────────────────────────────────────────────────────────────────────
#  AI DISCLAIMER  (printed on every AI-generated block in the report)
# ─────────────────────────────────────────────────────────────────────────────
AI_DISCLAIMER = (
    "AI-ASSISTED INTERPRETATION — Generated by Claude (claude-sonnet-4-6). "
    "This analysis supplements manual verification; it does not replace it. "
    "Always confirm findings in a controlled lab environment before reporting."
)


# ─────────────────────────────────────────────────────────────────────────────
#  ANALYSIS PROMPT  (structured for JSON output)
# ─────────────────────────────────────────────────────────────────────────────

def _build_prompt(finding: dict) -> str:
    return f"""You are a senior application security analyst reviewing a vulnerability scan result.

A Python-based Open Redirect detection tool found the following:

  URL Tested      : {finding.get('test_url', 'N/A')}
  Injected Param  : {finding.get('param', 'N/A')}
  Payload Used    : {finding.get('payload', 'N/A')}
  Server Status   : HTTP {finding.get('status_code', 'N/A')}
  Location Header : {finding.get('location', 'N/A')}
  Detection Type  : {finding.get('detection_type', 'N/A')}
  Tool Severity   : {finding.get('severity', 'N/A')}
  Evidence Note   : {finding.get('evidence', 'N/A')}

Provide a professional security analysis in the following JSON format only.
Return ONLY the JSON object — no markdown fences, no preamble.

{{
  "plain_english_explanation": "A 2-3 sentence explanation a non-technical stakeholder could understand.",
  "attack_scenario": "A concrete, realistic attack scenario showing how an adversary would exploit this.",
  "severity_label": "HIGH or MEDIUM or LOW",
  "severity_reasoning": "Why you chose this severity. Reference CVSS factors (network vector, user interaction, impact).",
  "cvss_estimate": "e.g. 6.1 (CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N)",
  "remediation_steps": [
    "Step 1: ...",
    "Step 2: ...",
    "Step 3: ..."
  ],
  "code_example": "A short Python/pseudocode snippet showing a secure redirect validation pattern.",
  "false_positive_notes": "Could this be a false positive? Under what conditions?"
}}"""


# ─────────────────────────────────────────────────────────────────────────────
#  PARSE AI RESPONSE  (safe JSON extraction with fallback)
# ─────────────────────────────────────────────────────────────────────────────

def _parse_response(raw_text: str) -> dict:
    """
    Extract JSON from the model's response.
    Handles markdown fences and leading/trailing whitespace.
    Falls back to storing raw text if parsing fails.
    """
    # Strip markdown code fences if present
    cleaned = re.sub(r"```(?:json)?", "", raw_text).strip()

    # Try direct parse
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        pass

    # Try extracting the first {...} block
    match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            pass

    # Fallback: store raw text so the report still includes something
    return {"raw_response": raw_text, "parse_error": "Could not parse JSON from model response."}


# ─────────────────────────────────────────────────────────────────────────────
#  MAIN ANALYSIS FUNCTION
# ─────────────────────────────────────────────────────────────────────────────

def analyze_with_ai(findings: list) -> list:
    """
    Enrich each vulnerable finding with AI-assisted analysis.
    Safe (non-vulnerable) findings get a minimal note instead.

    Args:
        findings : List of result dicts from detector.scan_target()

    Returns:
        The same list, with each dict enriched by an 'ai_analysis' key.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print(
            "\n  [WARN] ANTHROPIC_API_KEY not set — skipping AI analysis.\n"
            "         Set it with: export ANTHROPIC_API_KEY='sk-ant-...'\n"
        )
        for f in findings:
            f["ai_analysis"] = {
                "enabled": False,
                "note": "AI analysis skipped — ANTHROPIC_API_KEY not found.",
            }
        return findings

    client = anthropic.Anthropic(api_key=api_key)

    vulnerable = [f for f in findings if f.get("vulnerable")]
    print(f"\n  [AI]  Analyzing {len(vulnerable)} vulnerable finding(s) with Claude...")

    for finding in findings:
        # ── Skip safe findings ────────────────────────────────────────────────
        if not finding.get("vulnerable"):
            finding["ai_analysis"] = {
                "enabled": False,
                "note": "No vulnerability detected — AI analysis not needed.",
            }
            continue

        print(f"        → ?{finding['param']}  ({finding['test_url'][:55]}...)")

        try:
            prompt = _build_prompt(finding)

            message = client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=1000,
                messages=[{"role": "user", "content": prompt}],
            )

            raw_text  = message.content[0].text
            ai_data   = _parse_response(raw_text)

            finding["ai_analysis"] = {
                "enabled":    True,
                "disclaimer": AI_DISCLAIMER,
                "model":      "claude-sonnet-4-6",
                **ai_data,
            }

        except anthropic.AuthenticationError:
            finding["ai_analysis"] = {
                "enabled": False,
                "error":   "Authentication failed. Check your ANTHROPIC_API_KEY.",
            }
            print("  [ERR] Authentication error — stopping AI analysis.")
            break

        except anthropic.RateLimitError:
            finding["ai_analysis"] = {
                "enabled": False,
                "error":   "Rate limit reached. Wait and re-run with --ai-analysis.",
            }
            print("  [ERR] Rate limit hit — stopping AI analysis.")
            break

        except Exception as e:
            finding["ai_analysis"] = {
                "enabled": False,
                "error":   f"Unexpected error: {e}",
            }
            print(f"  [ERR] AI analysis failed for this finding: {e}")

    print("  [AI]  Analysis complete.")
    return findings
